build a spider for mohangi.com
rimsha-zaib/scrapy_training pull request #1
Opened 2024-03-22 19:38 UTC by rimsha-zaib

2024-03-29 09:56 UTC, faisal05sa requested changes
Overall it is good, I have observed a little room for improvement.

2024-03-29 09:56 UTC, faisal05sa commented on clothing_spider/clothing_spider/spiders/mohangi_spider.py
> +        pagination_links.add(response.url + '?page=1')
What if the URL already has some parameters? You may use [w3lib](https://w3lib.readthedocs.io/en/latest/) for handling such cases.

2024-04-01 09:11 UTC, rimsha-zaib commented on clothing_spider/clothing_spider/spiders/mohangi_spider.py
> +        pagination_links.add(response.url + '?page=1')
Done

2024-04-05 10:10 UTC, faisal05sa approved these changes

2024-04-05 10:10 UTC, merged